### PR TITLE
Add documentation for using `Authorisation headers` in rake taks

### PR DESCRIPTION
**Pull request by LeipeLeon**
Related to graphiti-api/graphiti-rails#70

### CODE REVIEW

**Comment by richmolj** [comment]
Thanks so much for following up @LeipeLeon ❤️ ! Some minor misspellings here though, .e.g. "autorisation"

**Comment by LeipeLeon** [comment]
🤦 

fixed!

**Comment by richmolj** [comment]
No worries! I speak only one language because two is too hard :) "Authorization" though not "Authorisation" as well

**Comment by LeipeLeon** [comment]
Fixed again :P

**Comment by LeipeLeon** [comment]
TIL: the difference between `Authorization` vs `Authorisation`

https://english.stackexchange.com/questions/282621/authorization-vs-authorisation-im-in-some-real-dilemma

**Comment by richmolj** [comment]
Awesome, thanks for sticking with it! 👏 🏅

**Pull request merged**
